from mongoengine import Document, StringField, IntField, BooleanField



class Template1(Document):

    name = StringField()
    street_address = StringField()
    Phonenumber = IntField()
    Email= StringField()
    city = StringField()
    country = StringField()
    university = StringField()
    uni_location = StringField()
    major = StringField()
    graduation_date = StringField()
    GPA = StringField()
    SAT = StringField()
    Honors = StringField()
    Relevant_Coursework = StringField()
    Company1 = StringField()
    Company1_location = StringField()
    Company1_Position = StringField()
    Company1_duration = StringField()
    Company1_Bullet1 = StringField()
    Company1_Bullet2 = StringField()
    Company1_Bullet3 = StringField()
    Company1_Bullet4 = StringField()
    Company2 = StringField()
    Company2_location = StringField()
    Company2_Position = StringField()
    Company2_duration = StringField()
    Company2_Bullet1 = StringField()
    Company2_Bullet2 = StringField()
    Company2_Bullet3 = StringField()
    Company2_Bullet4 = StringField()
    Company3 = StringField()
    Company3_location = StringField()
    Company3_Position = StringField()
    Company3_duration = StringField()
    Company3_Bullet1 = StringField()
    Company3_Bullet2 = StringField()
    Company3_Bullet3 = StringField()
    Company3_Bullet4 = StringField()
    Languages = StringField()
    Technical_skills = StringField()
    Training = StringField()
    Activities = StringField()
    Interests = StringField()
